language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
install:
  - pip install .
  - pip install -r test/requirements.txt
  - export PATH="$HOME/.local/bin:$PATH"
script:
  - nosetests
