# This file is part of Peach-Py package and is licensed under the Simplified BSD license.
#    See license.rst for the full text of the license.


import sys

import peachpy.x86_64.abi
import peachpy.x86_64.uarch
import peachpy.x86_64.isa


from peachpy.x86_64.registers import GeneralPurposeRegister, \
    GeneralPurposeRegister8, GeneralPurposeRegister16, GeneralPurposeRegister32, GeneralPurposeRegister64, \
    MMXRegister, XMMRegister, YMMRegister, \
    rax, rbx, rcx, rdx, rsi, rdi, rbp, r8, r9, r10, r11, r12, r13, r14, r15, \
    eax, ebx, ecx, edx, esi, edi, ebp, r8d, r9d, r10d, r11d, r12d, r13d, r14d, r15d, \
    ax, bx, cx, dx, si, di, bp, r8w, r9w, r10w, r11w, r12w, r13w, r14w, r15w, \
    al, ah, bl, bh, cl, ch, dl, dh, sil, dil, bpl, r8b, r9b, r10b, r11b, r12b, r13b, r14b, r15b, \
    mm0, mm1, mm2, mm3, mm4, mm5, mm6, mm7, \
    xmm0, xmm1, xmm2, xmm3, xmm4, xmm5, xmm6, xmm7, xmm8, xmm9, xmm10, xmm11, xmm12, xmm13, xmm14, xmm15, \
    ymm0, ymm1, ymm2, ymm3, ymm4, ymm5, ymm6, ymm7, ymm8, ymm9, ymm10, ymm11, ymm12, ymm13, ymm14, ymm15, \
    rip
from peachpy.x86_64.function import Function, LocalVariable
from peachpy.x86_64.operand import byte, word, dword, qword, oword, hword

from peachpy.x86_64.pseudo import Label, Loop, \
    LABEL, ALIGN, RETURN, LOAD, BROADCAST, STORE, ASSUME, INIT, REDUCE, SWAP
from peachpy.x86_64.nacl import NACLJMP

from peachpy.x86_64.generic import \
    ADD, SUB, ADC, SBB, ADCX, ADOX, \
    AND, OR, XOR, ANDN, \
    NOT, NEG, INC, DEC, \
    TEST, CMP, \
    MOV, MOVZX, MOVSX, MOVSXD, MOVBE, MOVNTI, \
    BT, BTS, BTR, BTC, POPCNT, BSWAP, \
    BSF, BSR, LZCNT, TZCNT, \
    SHR, SAR, SHL, SAL, SHRX, SARX, SHLX, \
    SHRD, SHLD, \
    ROR, ROL, RORX, \
    RCR, RCL, \
    IMUL, MUL, MULX, \
    IDIV, DIV, \
    LEA, PUSH, POP, \
    POPCNT, LZCNT, TZCNT, \
    BEXTR, PDEP, PEXT, \
    BZHI, \
    BLCFILL, BLCI, BLCIC, BLCMSK, BLCS, \
    BLSFILL, BLSI, BLSIC, BLSMSK, BLSR, \
    T1MSKC, TZMSK, \
    CRC32, \
    CBW, CDQ, CQO, \
    CWD, CWDE, CDQE, \
    CMOVA, CMOVNA, CMOVAE, CMOVNAE, \
    CMOVB, CMOVNB, CMOVBE, CMOVNBE, \
    CMOVC, CMOVNC, CMOVE, CMOVNE, \
    CMOVG, CMOVNG, CMOVGE, CMOVNGE, \
    CMOVL, CMOVNL, CMOVLE, CMOVNLE, \
    CMOVO, CMOVNO, CMOVP, CMOVNP, \
    CMOVS, CMOVNS, CMOVZ, CMOVNZ, \
    CMOVPE, CMOVPO, \
    SETA, SETNA, SETAE, SETNAE, \
    SETB, SETNB, SETBE, SETNBE, \
    SETC, SETNC, SETE, SETNE, \
    SETG, SETNG, SETGE, SETNGE, \
    SETL, SETNL, SETLE, SETNLE, \
    SETO, SETNO, SETP, SETNP, \
    SETS, SETNS, SETZ, SETNZ, \
    SETPE, SETPO, \
    JA, JNA, JAE, JNAE, \
    JB, JNB, JBE, JNBE, \
    JC, JNC, JE, JNE, \
    JG, JNG, JGE, JNGE, \
    JL, JNL, JLE, JNLE, \
    JO, JNO, JP, JNP, \
    JS, JNS, JZ, JNZ, \
    JPE, JPO, JMP, \
    JRCXZ, JECXZ, \
    RET, CALL, \
    PAUSE, NOP, \
    INT, UD2, \
    CPUID, RDTSC, RDTSCP, XGETBV, \
    STC, CLC, CMC, \
    STD, CLD, \
    XADD, XCHG, \
    CMPXCHG, CMPXCHG8B, CMPXCHG16B, \
    SFENCE, MFENCE, LFENCE, \
    PREFETCHNTA, PREFETCHT0, PREFETCHT1, PREFETCHT2, \
    PREFETCHW, PREFETCHWT1

from peachpy.x86_64.mmxsse import \
    MOVSS, EXTRACTPS, INSERTPS, \
    ADDSS, SUBSS, MULSS, DIVSS, SQRTSS, \
    ROUNDSS, MINSS, MAXSS, RCPSS, RSQRTSS, \
    CMPSS, COMISS, UCOMISS, \
    MOVSD, ADDSD, SUBSD, MULSD, DIVSD, SQRTSD, \
    ROUNDSD, MINSD, MAXSD, \
    CMPSD, COMISD, UCOMISD, \
    MOVAPS, MOVUPS, MOVLPS, MOVNTPS, \
    MOVHPS, MOVSLDUP, MOVSHDUP, \
    MOVAPD, MOVUPD, MOVLPD, MOVNTPD, \
    MOVHPD, MOVDDUP, \
    ADDPS, HADDPS, SUBPS, HSUBPS, ADDSUBPS, MULPS, DIVPS, SQRTPS, \
    ADDPD, HADDPD, SUBPD, HSUBPD, ADDSUBPD, MULPD, DIVPD, SQRTPD, \
    ROUNDPS, MINPS, MAXPS, RCPPS, RSQRTPS, DPPS, \
    CMPPS, MOVMSKPS, \
    ROUNDPD, MINPD, MAXPD, DPPD, \
    CMPPD, MOVMSKPD, \
    ANDPS, ANDNPS, ORPS, XORPS, BLENDPS, BLENDVPS, \
    ANDPD, ANDNPD, ORPD, XORPD, BLENDPD, BLENDVPD, \
    UNPCKLPS, UNPCKHPS, MOVLHPS, MOVHLPS, SHUFPS, \
    UNPCKLPD, UNPCKHPD, SHUFPD, \
    MOVD, MOVQ, MOVDQ2Q, MOVQ2DQ, MOVDQA, MOVDQU, LDDQU, \
    MASKMOVQ, MASKMOVDQU, \
    MOVNTQ, MOVNTDQ, MOVNTDQA, \
    PMOVSXBW, PMOVSXBD, PMOVSXBQ, PMOVSXWD, PMOVSXWQ, PMOVSXDQ, \
    PMOVZXBW, PMOVZXBD, PMOVZXBQ, PMOVZXWD, PMOVZXWQ, PMOVZXDQ, \
    PEXTRB, PEXTRW, PEXTRD, PEXTRQ, \
    PINSRB, PINSRW, PINSRD, PINSRQ, \
    PMOVMSKB, PTEST, \
    PADDB, PADDW, PADDD, PADDQ, PADDSB, PADDSW, PADDUSB, PADDUSW, \
    PHADDW, PHADDD, PHADDSW, \
    PSUBB, PSUBW, PSUBD, PSUBQ, PSUBSB, PSUBSW, PSUBUSB, PSUBUSW, \
    PHSUBW, PHSUBD, PHSUBSW, \
    PMAXSB, PMAXSW, PMAXSD, PMAXUB, PMAXUW, PMAXUD, \
    PMINSB, PMINSW, PMINSD, PMINUB, PMINUW, PMINUD, \
    PSLLW, PSLLD, PSLLQ, PSRLW, PSRLD, PSRLQ, PSRAW, PSRAD, \
    PMULLW, PMULHW, PMULHUW, PMULLD, PMULDQ, PMULUDQ, \
    PMULHRSW, PMADDWD, PMADDUBSW, \
    PAVGB, PAVGW, \
    PSADBW, MPSADBW, PHMINPOSUW, \
    PCMPEQB, PCMPEQW, PCMPEQD, PCMPEQQ, \
    PCMPGTB, PCMPGTW, PCMPGTD, PCMPGTQ, \
    PABSB, PABSW, PABSD, PSIGNB, PSIGNW, PSIGND, \
    PAND, PANDN, POR, PXOR, PBLENDW, PBLENDVB, \
    PUNPCKLBW, PUNPCKLWD, PUNPCKLDQ, PUNPCKLQDQ, \
    PUNPCKHBW, PUNPCKHWD, PUNPCKHDQ, PUNPCKHQDQ, \
    PACKSSWB, PACKSSDW, PACKUSWB, PACKUSDW, \
    PSHUFB, PSHUFW, PSHUFLW, PSHUFHW, PSHUFD, \
    PSLLDQ, PSRLDQ, PALIGNR, \
    PCMPESTRI, PCMPESTRM, PCMPISTRI, PCMPISTRM, \
    CVTSS2SI, CVTTSS2SI, CVTSI2SS, \
    CVTSD2SI, CVTTSD2SI, CVTSI2SD, \
    CVTPS2DQ, CVTTPS2DQ, CVTDQ2PS, \
    CVTPD2DQ, CVTTPD2DQ, CVTDQ2PD, \
    CVTPS2PI, CVTTPS2PI, CVTPI2PS, \
    CVTPD2PI, CVTTPD2PI, CVTPI2PD, \
    CVTSD2SS, CVTSS2SD, \
    CVTPD2PS, CVTPS2PD, \
    LDMXCSR, STMXCSR, \
    EMMS

from peachpy.x86_64.avx import \
    VMOVSS, VEXTRACTPS, VINSERTPS, \
    VADDSS, VSUBSS, VMULSS, VDIVSS, VSQRTSS, \
    VROUNDSS, VMINSS, VMAXSS, VRCPSS, VRSQRTSS, \
    VCMPSS, VCOMISS, VUCOMISS, \
    VMOVSD, VADDSD, VSUBSD, VMULSD, VDIVSD, VSQRTSD, \
    VROUNDSD, VMINSD, VMAXSD, \
    VCMPSD, VCOMISD, VUCOMISD, \
    VMOVAPS, VMOVUPS, VMOVLPS, VMOVHPS, \
    VMASKMOVPS, VMOVMSKPS, VMOVNTPS, \
    VBROADCASTSS, VMOVSLDUP, VMOVSHDUP, \
    VGATHERDPS, VGATHERQPS, \
    VMOVAPD, VMOVUPD, VMOVLPD, VMOVHPD, \
    VMASKMOVPD, VMOVMSKPD, VMOVNTPD, \
    VBROADCASTSD, VMOVDDUP, \
    VGATHERDPD, VGATHERQPD, \
    VADDPS, VHADDPS, VSUBPS, VHSUBPS, VADDSUBPS, VMULPS, VDIVPS, VSQRTPS, \
    VADDPD, VHADDPD, VSUBPD, VHSUBPD, VADDSUBPD, VMULPD, VDIVPD, VSQRTPD, \
    VROUNDPS, VMINPS, VMAXPS,  VRCPPS, VRSQRTPS, VDPPS, \
    VCMPPS, VTESTPS, \
    VROUNDPD, VMINPD, VMAXPD, VDPPD, \
    VCMPPD, VTESTPD, \
    VANDPS, VANDNPS, VORPS, VXORPS, VBLENDPS, VBLENDVPS, \
    VANDPD, VANDNPD, VORPD, VXORPD, VBLENDPD, VBLENDVPD, \
    VUNPCKLPS, VUNPCKHPS, VMOVLHPS, VMOVHLPS, VSHUFPS, VPERMPS, VPERMILPS, \
    VUNPCKLPD, VUNPCKHPD, VSHUFPD, VPERMPD, VPERMILPD, \
    VMOVD, VMOVQ, VMOVDQA, VMOVDQU, VLDDQU, \
    VPMASKMOVD, VPMASKMOVQ, VMASKMOVDQU, VMOVNTDQ, VMOVNTDQA, \
    VPMOVSXBW, VPMOVSXBD, VPMOVSXBQ, VPMOVSXWD, VPMOVSXWQ, VPMOVSXDQ, \
    VPMOVZXBW, VPMOVZXBD, VPMOVZXBQ, VPMOVZXWD, VPMOVZXWQ, VPMOVZXDQ, \
    VPEXTRB, VPEXTRW, VPEXTRD, VPEXTRQ, \
    VPINSRB, VPINSRW, VPINSRD, VPINSRQ, \
    VPGATHERDD, VPGATHERDQ, VPGATHERQD, VPGATHERQQ, \
    VPTEST, VPMOVMSKB, \
    VPADDB, VPADDW, VPADDD, VPADDQ, VPADDSB, VPADDSW, VPADDUSB, VPADDUSW, \
    VPHADDW, VPHADDD, VPHADDSW, \
    VPSUBB, VPSUBW, VPSUBD, VPSUBQ, VPSUBSB, VPSUBSW, VPSUBUSB, VPSUBUSW, \
    VPHSUBW, VPHSUBD, VPHSUBSW, \
    VPMAXSB, VPMAXSW, VPMAXSD, VPMAXUB, VPMAXUW, VPMAXUD, \
    VPMINSB, VPMINSW, VPMINSD, VPMINUB, VPMINUW, VPMINUD, \
    VPSLLW, VPSLLD, VPSLLQ, VPSRLW, VPSRLD, VPSRLQ, VPSRAW, VPSRAD, \
    VPSLLVD, VPSLLVQ, VPSRLVD, VPSRLVQ, VPSRAVD, \
    VPMULLW, VPMULHW, VPMULHUW, VPMULLD, VPMULDQ, VPMULUDQ, \
    VPMULHRSW, VPMADDWD, VPMADDUBSW, \
    VPAVGB, VPAVGW, \
    VPSADBW, VMPSADBW, VPHMINPOSUW, \
    VPCMPEQB, VPCMPEQW, VPCMPEQD, VPCMPEQQ, \
    VPCMPGTB, VPCMPGTW, VPCMPGTD, VPCMPGTQ, \
    VPABSB, VPABSW, VPABSD, VPSIGNB, VPSIGNW, VPSIGND, \
    VPAND, VPANDN, VPOR, VPXOR, VPBLENDW, VPBLENDVB, VPBLENDD, \
    VPUNPCKLBW, VPUNPCKLWD, VPUNPCKLDQ, VPUNPCKLQDQ, \
    VPUNPCKHBW, VPUNPCKHWD, VPUNPCKHDQ, VPUNPCKHQDQ, \
    VPACKSSWB, VPACKSSDW, VPACKUSWB, VPACKUSDW, \
    VPSHUFB, VPSHUFLW, VPSHUFHW, VPSHUFD, VPERMD, VPERMQ, \
    VPSLLDQ, VPSRLDQ, VPALIGNR, \
    VPBROADCASTB, VPBROADCASTW, VPBROADCASTD, VPBROADCASTQ, \
    VPCMPESTRI, VPCMPESTRM, VPCMPISTRI, VPCMPISTRM, \
    VCVTSS2SI, VCVTTSS2SI, VCVTSI2SS, \
    VCVTSD2SI, VCVTTSD2SI, VCVTSI2SD, \
    VCVTPS2DQ, VCVTTPS2DQ, VCVTDQ2PS, \
    VCVTPD2DQ, VCVTTPD2DQ, VCVTDQ2PD, \
    VCVTSD2SS, VCVTSS2SD, \
    VCVTPD2PS, VCVTPS2PD, \
    VCVTPS2PH, VCVTPH2PS, \
    VBROADCASTF128, VBROADCASTI128, \
    VEXTRACTF128, VEXTRACTI128, \
    VINSERTF128, VINSERTI128, \
    VPERM2F128, VPERM2I128, \
    VLDMXCSR, VSTMXCSR, \
    VZEROUPPER, VZEROALL

from peachpy.x86_64.fma import \
    VFMADD132SS,  VFMADD213SS,  VFMADD231SS,  VFMADDSS, \
    VFMSUB132SS,  VFMSUB213SS,  VFMSUB231SS,  VFMSUBSS, \
    VFNMADD132SS, VFNMADD213SS, VFNMADD231SS, VFNMADDSS, \
    VFNMSUB132SS, VFNMSUB213SS, VFNMSUB231SS, VFNMSUBSS, \
    VFMADD132SD,  VFMADD213SD,  VFMADD231SD,  VFMADDSD, \
    VFMSUB132SD,  VFMSUB213SD,  VFMSUB231SD,  VFMSUBSD, \
    VFNMADD132SD, VFNMADD213SD, VFNMADD231SD, VFNMADDSD, \
    VFNMSUB132SD, VFNMSUB213SD, VFNMSUB231SD, VFNMSUBSD, \
    VFMADD132PS,  VFMADD213PS,  VFMADD231PS,  VFMADDPS, \
    VFMSUB132PS,  VFMSUB213PS,  VFMSUB231PS,  VFMSUBPS, \
    VFNMADD132PS, VFNMADD213PS, VFNMADD231PS, VFNMADDPS, \
    VFNMSUB132PS, VFNMSUB213PS, VFNMSUB231PS, VFNMSUBPS, \
    VFMADD132PD,  VFMADD213PD,  VFMADD231PD,  VFMADDPD, \
    VFMSUB132PD,  VFMSUB213PD,  VFMSUB231PD,  VFMSUBPD, \
    VFNMADD132PD, VFNMADD213PD, VFNMADD231PD, VFNMADDPD, \
    VFNMSUB132PD, VFNMSUB213PD, VFNMSUB231PD, VFNMSUBPD, \
    VFMADDSUB132PS, VFMADDSUB213PS, VFMADDSUB231PS, VFMADDSUBPS, \
    VFMSUBADD132PS, VFMSUBADD213PS, VFMSUBADD231PS, VFMSUBADDPS, \
    VFMADDSUB132PD, VFMADDSUB213PD, VFMADDSUB231PD, VFMADDSUBPD, \
    VFMSUBADD132PD, VFMSUBADD213PD, VFMSUBADD231PD, VFMSUBADDPD

from peachpy.x86_64.crypto import \
    AESDEC, AESDECLAST, AESENC, AESENCLAST, AESIMC, AESKEYGENASSIST, \
    VAESDEC, VAESDECLAST, VAESENC, VAESENCLAST, VAESIMC, VAESKEYGENASSIST, \
    SHA1MSG1, SHA1MSG2, SHA1NEXTE, SHA1RNDS4, SHA256MSG1, SHA256MSG2, SHA256RNDS2, \
    PCLMULQDQ, VPCLMULQDQ, \
    RDRAND, RDSEED

from peachpy.x86_64.amd import \
    PAVGUSB, PMULHRW, \
    PF2ID, PF2IW, PI2FW, PI2FD, \
    PFADD, PFSUB, PFSUBR, PFMUL, PFMAX, PFMIN, \
    PFACC, PFNACC, PFPNACC, PSWAPD, \
    PFCMPEQ, PFCMPGT, PFCMPGE, \
    PFRCP, PFRCPIT1, PFRCPIT2, PFRSQRT, PFRSQIT1, \
    FEMMS, \
    MOVNTSS, MOVNTSD, \
    INSERTQ, EXTRQ, \
    VPPERM, VPCMOV, \
    VPROTB, VPROTW, VPROTD, VPROTQ, \
    VPSHAB, VPSHAW, VPSHAD, VPSHAQ, \
    VPSHLB, VPSHLW, VPSHLD, VPSHLQ, \
    VPCOMB, VPCOMW, VPCOMD, VPCOMQ, \
    VPCOMUB, VPCOMUW, VPCOMUD, VPCOMUQ, \
    VPHADDBW, VPHADDBD, VPHADDBQ, VPHADDWD, VPHADDWQ, VPHADDDQ, \
    VPHADDUBW, VPHADDUBD, VPHADDUBQ, VPHADDUWD, VPHADDUWQ, VPHADDUDQ, \
    VPHSUBBW, VPHSUBWD, VPHSUBDQ, \
    VPMACSDQH, VPMACSDQL, VPMACSDD, VPMACSWD, VPMACSWW, VPMADCSWD, \
    VPMACSSDD, VPMACSSDQH, VPMACSSDQL, VPMACSSWD, VPMACSSWW, VPMADCSSWD, \
    VFRCZSS, VFRCZSD, VFRCZPS, VFRCZPD, \
    VPERMIL2PD, VPERMIL2PS

from peachpy.x86_64.types import \
    m64, m128, m128d, m128i, m256, m256d, m256i, m512, m512d, m512i, mmask8, mmask16
